# Generated by Django 5.1.6 on 2025-06-30 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JollofandChillHeroHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_head', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_description', models.TextField()),
                ('hero_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('hero_img', models.ImageField(upload_to='hero_images/')),
                ('hero_publish_date', models.DateTimeField(auto_now_add=True)),
                ('hero_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hero_publish_date'],
            },
        ),
    ]
