# Generated by Django 5.1.6 on 2025-07-02 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollofandchill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondJollofandChillPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_jollof_and_chill_title', models.CharField(blank=True, max_length=255, null=True)),
                ('second_jollof_and_chill_description', models.TextField()),
                ('second_jollof_and_chill_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('second_jollof_and_chill_img', models.ImageField(upload_to='hero_images/')),
                ('second_jollof_and_chill_publish_date', models.DateTimeField(auto_now_add=True)),
                ('second_jollof_and_chill_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-second_jollof_and_chill_publish_date'],
            },
        ),
    ]
