# Generated by Django 5.1.6 on 2025-07-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollofandchill', '0002_secondjollofandchillpostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondjollofandchillpostmodel',
            name='second_jollof_and_chill_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
