# Generated by Django 5.1.6 on 2025-07-02 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollofandchill', '0003_alter_secondjollofandchillpostmodel_second_jollof_and_chill_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewJollofandChill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(blank=True, max_length=255, null=True)),
                ('review_profession', models.CharField(blank=True, max_length=255, null=True)),
                ('review_description', models.TextField()),
                ('review_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('review_img', models.ImageField(upload_to='review_images/')),
                ('review_publish_date', models.DateTimeField(auto_now_add=True)),
                ('review_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_publish_date'],
            },
        ),
    ]
