# Generated by Django 5.1.6 on 2025-07-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollofandchill', '0004_reviewjollofandchill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuJollofandChil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_description', models.TextField()),
                ('menu_img', models.ImageField(upload_to='menu_images/')),
                ('item1', models.DecimalField(decimal_places=2, default=0.0, max_digits=70)),
                ('item2', models.DecimalField(decimal_places=2, default=0.0, max_digits=70)),
                ('item3', models.DecimalField(decimal_places=2, default=0.0, max_digits=70)),
                ('item4', models.DecimalField(decimal_places=2, default=0.0, max_digits=70)),
                ('item5', models.DecimalField(decimal_places=2, default=0.0, max_digits=70)),
                ('item6', models.DecimalField(decimal_places=2, default=0.0, max_digits=70)),
                ('item7', models.DecimalField(decimal_places=2, default=0.0, max_digits=70)),
                ('item8', models.DecimalField(decimal_places=2, default=0.0, max_digits=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
