# Generated by Django 5.1.6 on 2025-07-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollofandchill', '0005_menujollofandchil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menujollofandchil',
            options={'ordering': ['-created_at']},
        ),
    ]
