# Generated by Django 5.1.6 on 2025-07-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollofandchill', '0006_alter_menujollofandchil_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menujollofandchil',
            old_name='item1',
            new_name='Fried_Plantain',
        ),
        migrations.RenameField(
            model_name='menujollofandchil',
            old_name='item2',
            new_name='meat_pie',
        ),
        migrations.RemoveField(
            model_name='menujollofandchil',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='menujollofandchil',
            name='item4',
        ),
        migrations.RemoveField(
            model_name='menujollofandchil',
            name='item5',
        ),
        migrations.RemoveField(
            model_name='menujollofandchil',
            name='item6',
        ),
        migrations.RemoveField(
            model_name='menujollofandchil',
            name='item7',
        ),
        migrations.RemoveField(
            model_name='menujollofandchil',
            name='item8',
        ),
    ]
