# Generated by Django 5.1.6 on 2025-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollofandchill', '0007_rename_item1_menujollofandchil_fried_plantain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menujollofandchil',
            name='Fried_Plantain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menujollofandchil',
            name='meat_pie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
