# Generated by Django 5.1.6 on 2025-07-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollofandchill', '0008_alter_menujollofandchil_fried_plantain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menujollofandchil',
            old_name='Fried_Plantain',
            new_name='item1',
        ),
        migrations.RenameField(
            model_name='menujollofandchil',
            old_name='meat_pie',
            new_name='item2',
        ),
    ]
