# Generated by Django 5.1.6 on 2025-07-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollofandchill', '0009_rename_fried_plantain_menujollofandchil_item1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menujollofandchil',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='menujollofandchil',
            name='item2',
        ),
    ]
